# Generated by Django 4.0.6 on 2022-07-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
        ('wallet', '0002_alter_wallet_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='transaction',
            field=models.ManyToManyField(blank=True, related_name='History', to='transaction.transaction'),
        ),
    ]
