# Ejercicio 1
""" a = 2.4
b = -3.21
c = 47.8

print("a\tb\tc")
print(a,"\t", b, "\t", c)
"""
# ---------------------------------------

print("Imagen de Python con caracteres ASCII")
print()
print("""
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0OOkkxxxxxxxxxkkO00KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0kxolc:;,,''''''''''''''',,;:cldxk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOxl:;,''''''''''',,,,,,,,,,,''''''''''',;cok0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc;,'''''',,;;;::ccccclllllllcccc:::;;,,''''''',:oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o:,''''',;;:cllloooooooooooooooooooooooolllc::;,,'''',:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl,'''',;:clloooooooooollllllllllllllllllooooooooolc:;,'''';dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKo,''',;:loodkO000Odolcccccccccccccccccccccclllllloooooll:,''',c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc'''';cooodkXWMMMMWNOoccccccccccccccccccccccccccccllloooool;,'''c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,''';looookNMMMMMMMMWOlccccccccccccccccccccccccccccccllooool:''''oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc''',cddoookNMMMMMMMMMKocccccccccccccccccccccccccccccccclooool,''':0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc''',ldddolo0WMMMMMMWNkllllllllllllllccccccccccccccccccclooool;''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc''',ldddollokKXNNNKOdlllllllllllllllllllllllllllllllllllooool;''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc''';ldddoollllodddolllllllllllllllllllllllllllllllllllllooodl;''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc''';lddddoooooooooooooooooooooooooooooooolllllllllllllllodddl;''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc''';lddddddddddddddddddddddddddddddddddddollllllllllllllodddo;''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNNO:''';looooooooooooooooooooooooooooooodddddollllllllllllloddddl;''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWN0kdolc::::::::::::,'''',,,,,,;;;;;,,,,,;;;;;;,,,,,,,,;;lddddollllllllllllloddolc;''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMW0dc,'''''''''''''''''''''''''''''''''''''''''''''''''''',,cddddoooooololoollllllllc;''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWKo;'''',;::::::::::::::::::::::::::::::::::::::::::::::::::cldddddoooooooolllc::clllc;''';xKKKKKKKKKKKKKKKKKXXNWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMNk:''',;codxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddxxxxddooooollcc::;;:clllc;''',codoooooooooooooooddxkO0XWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMNd;''',cdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddolllcc:::::;;;:clllc;''',coooddddddddddddddoooooddkKNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMNx,''';lxxxxxdddddddddddddddddddddddddddddooooooooooooooooolllllllccc::::;;;;;:::;::clllc;''',cooodOKKKKKKKKKKKK0OkxdooodkKWMMMMMMMMMMMMMM
MMMMMMMMMMMNx;''';oxxxxddddddddddddddddddddooollllcccccc:::::::::::::::::::::::::::::;;::::::;;:clllc;''',coood0NNNNNNNNNNNNNNNXKkdooodONMMMMMMMMMMMMM
MMMMMMMMMMWO:''',lxxxxxdddddddddddddddoollccc::::::::::::::::::::::::::::::::::;;::::::::;;::;;:clllc;''',coood0NNNNNNNNNNNNNNNNNN0xooodONMMMMMMMMMMMM
MMMMMMMMMMKl''',cxkxxxddddddddddddollcc::::::::::::::::::::::::::::::::::::::::;;::::::::;:::;;:clllc;''',coood0NNNNNXXXXXXXNNNNNNNKkooodOWMMMMMMMMMMM
MMMMMMMMMNd,''':dkkkxxddddddddollc:::::::::::::::::::::::::::::::::::::::::::::;;:::::::::::;;::clllc,''',coood0NNNNNXXXXXXXXXNNNNNNKxoooxKWMMMMMMMMMM
MMMMMMMMM0:''';okkkkxddddddolcc::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;::::clllc:,''';loooxKNNNNNXXXXXXXXXXNNNNNN0doookXMMMMMMMMMM
MMMMMMMMNd,'''cxkkkxxdddolc::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;::cclllc:,''',cooodONNNNNNNNXXNNNNNNNNNNNNXkdood0WMMMMMMMMM
MMMMMMMMKc''';okkkkxddocc::::::::::::::::::::::::::::::::::cc::::::::::::::::::::::::::::::ccclllc;,''',:ooooxKNWNNNNNNNNNNNNNNNNNNNWNKxoookXMMMMMMMMM
MMMMMMMMk;''':xkkkxdlc::::::::::::::::::::::::::::cccccllllllllllllllllllllllllllllllllllllllllc:,'''',cooodxKNNNNNNNNNNNNNNNNNNNNNNNWXkooodKWMMMMMMMM
MMMMMMMWx,'''ckkkxoc:::::::::::::::::::::::::::ccllllllllllllllllllllllllllllllllllllllllllcc:;,'''',:looodkKNNNNNNNNNNNNNNNNNNNNNNNWNN0doodONMMMMMMMM
MMMMMMMNd''',lxxolc:::::::::::::::::::::::::cclllllllcc::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,''''',;coooodOXNWNNNNNNNNNNNNNNNNNNNNNNWNNKxoooxXMMMMMMMM
MMMMMMMNd''',coollc:::::::::::::::::::::::cllllllc:;;,,'''''''''''''''''''''''''''''''''''''''',;:loooodkKNWWWWNNNNNNNNNNNNNNNNNNNNNWWWXkooodKWMMMMMMM
MMMMMMMNd,''':llllc:::::::::::::::::::::clllllc:;,''''''',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::clooooodkKNWWWWWNNNNNNNNNNNNNNNNNNNNNNWWNNOdood0WMMMMMMM
MMMMMMMWx,''';llllc:::::::::::::::::::clllllc:,''''',;:ccloooooooooooooooooooooooooooooooooooooooddk0XNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOdoodOWMMMMMMM
MMMMMMMMO;''';cllllc:::::::::::::::::clllll:,''''';:loooooooooooooooooooooooooooooooooooooooddxkO0XNWWWWWWNNNNNNNNNNNNNNNNNNNNNNNXXXNNNXOdoooOWMMMMMMM
MMMMMMMMKc''',cllllc::::::::::::::::cllllc;,'''';cooooddxkOO0000000000000000000000000000000KKXXNWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNXXKKXNNNXOdoooOWMMMMMMM
MMMMMMMMNo'''':llllc:::::::::::::::cllllc;'''',coooodk0XNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNXXXKKKKKXXNNXOdood0WMMMMMMM
MMMMMMMMWO;''';cllllc:::::::::::::cllllc;'''';looodOKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNXXXXKKKKKKKKKXXXNKkoooxKMMMMMMMM
MMMMMMMMMXl''',:llllc:::::::::::::cllll:'''';loood0NWWWWWWWWNWWWWNNNWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXKKKKKKKKKKKKKKKXXXXX0xoookXMMMMMMMM
MMMMMMMMMWk;''';cllllc:::::::::::cllllc,''',cooodONWWWWWWNNNNNNNNNNNWWWNNNNNNNNNNXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNNNXkdood0WMMMMMMMM
MMMMMMMMMMXl''',:lllllc::::::::::cllll:,''';loooxXWWWWWWWWWWWWWWWWWWWNNNNNXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNNX0xoooxXMMMMMMMMM
MMMMMMMMMMWO:''',:lllllc:::::::::cllll:,''';loooONWWWWWWWWWWWWWWWWWNNNXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNNKxoood0WMMMMMMMMM
MMMMMMMMMMMNx;''',:lllllccc::::::cllll:,''';loodONWWWWWWWWWWWWWWNNXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXOdoodONMMMMMMMMMM
MMMMMMMMMMMMNx;''',:llllllllllllllllll:,''';loooONWWWWWWWWWWWNNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXOdoooxXMMMMMMMMMMM
MMMMMMMMMMMMMNk:'''',:clllllllllllllll:,''';loodONWWWWWWWWNNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXX0xoooxKWMMMMMMMMMMM
MMMMMMMMMMMMMMW0o;'''',;;:::::::::::::;'''';loodONWWWWWNNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXX0doood0WMMMMMMMMMMMM
MMMMMMMMMMMMMMMMN0o:,'''''''''''''''''''''';loooONWWWWXXKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKkdooox0WMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWXOxoc:;,,,,,,,,,,,,,,,,,:loooONWWNXKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKK0kdooodkKWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWNXKK0000000000000000kdoooONNNXXKKKKKKKKKKKKKKKXXXX0kxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkxxxxxxxkkkkkkkkkkxxxddooodx0NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdoookXXXXXKKKKKKKKKKKKKKKXXXXOdoooooooooooooooooooooooooooooooooooooooooooooooooooodxk0NMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdoookKXXXXKKKKKKKKKKKKKKKXXXX0kxxkkxxkkkkkkkkkkkkkkkkkkkkkxxxxdooodkkkkkkkkkkkkOO0KXNWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdoookKXXXXKKK0KK0KKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0xoooxXWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWNN0doookKXXXXK00000000K000KKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0xoooxXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNXXXXKOdoookKXXXXK0000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXX0xoooxKNNNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNXXXXKKKK000kdoookKXXXXK00000000000000000000000000000000000KKXXXXKK00KXXXX0xooox0KKXXXXNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWWWWNNNXXXXKKK000OOOOkxdoookKXXXXK000000000000000000000000000000000KXNWMMMMWNXKKXXXX0xooodO000KKKXXXXNNNWWWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWWWNNNXXXKKK0000OOOkkkxxddoookKXXXXK00000000000000000000000000000000KXWMMMMMMMMWXKXXXX0xooodkOOO0000KKKXXXNNNWWWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWWWNNNXXXKKK000OOOkkkxxxdddoooox0XXXXK00000000000000000000000000000000KNMMMMMMMMMWNXXXXXOdooodxkkkOOO000KKKXXXNNNWWWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWWWNNNXXXKKK000OOOkkkxxxdddoooooodkKXXXXKKK000000000000000000000000000000XWMMMMMMMMWNXXXX0xooodddxxkkkOOO000KKKXXXNNNWWWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWWWNNXXXKKK000OOOkkxxxdddooolloooodk0XXXXXXKKK0000000000000000000000000000KNWWMMWWNNXXXKOdoooooddxxxkkkOOO000KKKXXXNNWWWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWWWNNNXXXKKK00OOOkkkxxxdddoollllooooodk0KXXXXXXXKKKKKK0000000000000000KKKKKKXXNNNNXXXK0kxooooooodddxxxkkkOOO00KKKXXXNNNWWWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWWWNNXXXKKK000OOOkkxxxdddooolllllooooodxk0KKXXXXXXXXXXXKKKKKKKKKKKKXXXXXXXXXXXXXK0OkxdooooooooodddxxkkkOOO000KKKXXXNNWWWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWWNNNXXXKKK000OOOkkkxxxdddooolllllooooooddxkOO0KKXXXXXXXXXXXXXXXXXXXXXXXKK00OkxxdooooooooooodddxxxkkkOOO000KKKXXXNNNWWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWWWNNNXXXKKK000OOOkkkxxxddddooollllloooooooodddxxkkOOO00000000000OOOkkxxdddoooooooooooooddddxxxkkkOOO000KKKXXXNNNWWWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWWWNNNXXXXKKK000OOOkkkkxxxddddooooooooooooooooooooooddddddddddddooooooooooooooooooddddxxxkkkkOOO000KKKKXXXNNNWWWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWWWNNNNXXXKKK0000OOOOkkkkxxxxdddddoooooooooooooooooooooooooooooooooooooddddddxxxxkkkkOOOO0000KKKXXXNNNWWWWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNXXXKKKK00000OOOOkkkkkxxxxxxxddddddddddddddddddddddddddddxxxxxxxkkkkkOOOO00000KKKXXXXNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNXXXXKKKKK00000OOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOO000000KKKKXXXXNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWNNNNNXXXXXKKKKKKKK000000000000000000000000000000KKKKKKKKXXXXXXNNNNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
""")




# ---------------------------------------

# Ejercicio 3
"""
palabra1 = input("Ingrese una palabra: ")
palabra2 = input("Ingrese una palabra: ")
palabra3 = input("Ingrese una palabra: ")

longitud_palabra1 = "*"*len(palabra1)
# print(palabra1, longitud_palabra1)

longitud_palabra2 = "*"*len(palabra2)
# print(palabra2, longitud_palabra2)

longitud_palabra3 = "*"*len(palabra3)
# print(palabra3, longitud_palabra3)
"""

# ---------------------------------------

# Ejercicio 4
"""
diccionario_palabras = {
  palabra1: longitud_palabra1,
  palabra2: longitud_palabra2,
  palabra3: longitud_palabra3,
}

# print(diccionario_palabras)

for x in diccionario_palabras:
  print("llave:", x, "valor:", diccionario_palabras[x])

"""