# Generated by Django 4.1.3 on 2022-12-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=40, verbose_name='Apellido')),
                ('contraseña', models.CharField(max_length=255, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
