# Generated by Django 4.1.3 on 2022-12-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_contraseña_usuario_contrasenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user_name',
            field=models.CharField(default='', max_length=40, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
