# Generated by Django 4.1.3 on 2022-12-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
