# Generated by Django 4.1.3 on 2022-12-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='User name'),
        ),
    ]
