# Generated by Django 4.1.3 on 2022-12-07 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterModelTable(
            name='nota',
            table='Nota',
        ),
    ]
