# Generated by Django 4.1.3 on 2022-12-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_nota_fecha_creacion_alter_nota_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nota',
            table='nota',
        ),
    ]
