# Generated by Django 4.1.3 on 2022-12-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_nota_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='contenido',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='titulo',
            field=models.CharField(max_length=160, verbose_name='Título'),
        ),
    ]
