# Generated by Django 4.1.3 on 2022-11-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=40, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
            ],
        ),
    ]
